GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/16

###
DELETE http://localhost:3001/api/persons/3

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "chair",
    "number": "13943"
}

###
GET https://part3-phonebook-white-river-322.fly.dev/api/persons

###
POST https://part3-phonebook-white-river-322.fly.dev/api/persons
Content-Type: application/json

{
    "name": "chair",
    "number": "13943"
}

